export const VmStatuses = Object.freeze({
  ACTIVE: "ACTIVE",
  BUILD: "BUILD",
  DELETED: "DELETED",
  ERROR: "ERROR",
  HARD_REBOOT: "HARD_REBOOT",
  MIGRATING: "MIGRATING",
  PASSWORD: "PASSWORD",
  PAUSED: "PAUSED",
  REBOOT: "REBOOT",
  REBUILD: "REBUILD",
  RESCUE: "RESCUE",
  RESIZE: "RESIZE",
});
